//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndrewPechaWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestThing2
    {
        public int ID { get; set; }
        public string word2 { get; set; }
        public decimal INT2 { get; set; }
    }
}
